name = "excited_plum_marlin-1643"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "excited_plum_marlin-1643-debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "excited_plum_marlin-1643-release.wasm"
command = "npm run build:release"
